// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GoBack: typeof import('./src/components/GoBack.vue')['default']
    HeadCps: typeof import('./src/components/HeadCps.vue')['default']
    HomeButton: typeof import('./src/components/HomeButton.vue')['default']
    LoadingCps: typeof import('./src/components/LoadingCps.vue')['default']
    LoadingIcon: typeof import('./src/components/icons/LoadingIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
